### ISSUE TITLE
Using restfulserver with namespaced Model classes?

### ISSUE THREAD

**Issue by bummzack** [silverstripe/silverstripe-restfulserver#37]
I can't seem to make this module work with namespaced model classes. Say that I have a model:
`Bummzack\Project\Model\MyDataObject` and I'd like to have it accessible via RESTful API.

I see two possible approaches (not mutually exclusive):

1) Use a different character instead of `\` in the URL, such as: `api/v1/Bummzack-Project-Model-MyDataObject`
2) Add a mapping table as a config setting. Something like the following:

```yml
RestfulServer:
  class_mapping:
    MyDataObject: Bummzack\Project\Model\MyDataObject
```

This change could also be useful when/if this modules gets updated for SilverStripe 4.0.
Should I create a PR for this?
